import { User, Building2, FileText, Calendar, Heart, MessageCircle, Download, Home, RotateCcw } from "lucide-react";
import ResultsCard from "./ResultsCard";
import jsPDF from "jspdf";

interface ResultsDashboardProps {
  show: boolean;
  results?: {
    name: string;
    company: string;
    summary: string;
    nextAction: string;
    sentiment: string;
    suggestedReply: string;
  } | null;
  onReset: () => void;
}

const ResultsDashboard = ({ show, results, onReset }: ResultsDashboardProps) => {
  if (!show || !results) return null;

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment.toLowerCase()) {
      case 'positive':
        return 'text-green-400';
      case 'negative':
        return 'text-red-400';
      default:
        return 'text-yellow-400';
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(99, 102, 241); // primary color
    doc.text('Z-CRM Contact Analysis', 20, 20);
    
    // Results
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    
    doc.text('Name:', 20, 40);
    doc.text(results.name, 60, 40);
    
    doc.text('Company:', 20, 55);
    doc.text(results.company, 60, 55);
    
    doc.text('Sentiment:', 20, 70);
    doc.text(results.sentiment, 60, 70);
    
    doc.text('Next Action:', 20, 85);
    const nextActionLines = doc.splitTextToSize(results.nextAction, 170);
    doc.text(nextActionLines, 20, 95);
    
    doc.text('Summary:', 20, 110 + (nextActionLines.length * 5));
    const summaryLines = doc.splitTextToSize(results.summary, 170);
    doc.text(summaryLines, 20, 120 + (nextActionLines.length * 5));
    
    doc.text('Suggested Reply:', 20, 135 + ((nextActionLines.length + summaryLines.length) * 5));
    const replyLines = doc.splitTextToSize(results.suggestedReply, 170);
    doc.text(replyLines, 20, 145 + ((nextActionLines.length + summaryLines.length) * 5));
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Z-CRM • Powered by AI', 20, 280);
    
    doc.save(`${results.name.replace(/\s+/g, '_')}_analysis.pdf`);
  };

  return (
    <section id="insights" className="mt-12 animate-fade-in">
      <div className="text-center mb-8 space-y-3">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-500/10 border border-green-500/20 animate-scale-in">
          <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
          <span className="text-sm font-medium text-green-500">Analysis Complete</span>
        </div>
        <h2 className="text-3xl font-bold">Your Insights</h2>
        <div className="flex items-center justify-center gap-3">
          <p className="text-muted-foreground">AI-powered analysis of your contact interaction</p>
          <button
            onClick={handleDownloadPDF}
            className="ios-glass-button px-4 py-2 rounded-xl text-sm font-medium flex items-center gap-2 hover:scale-105 transition-all duration-300 text-black"
          >
            <Download size={16} />
            Download Summary (PDF)
          </button>
        </div>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
        <ResultsCard
          icon={User}
          label="Name"
          value={results.name}
          iconColor="text-blue-400"
          delay={0}
        />
        <ResultsCard
          icon={Building2}
          label="Company"
          value={results.company}
          iconColor="text-purple-400"
          delay={100}
        />
        <ResultsCard
          icon={Heart}
          label="Sentiment"
          value={results.sentiment.charAt(0).toUpperCase() + results.sentiment.slice(1)}
          iconColor={getSentimentColor(results.sentiment)}
          delay={200}
        />
        <ResultsCard
          icon={Calendar}
          label="Next Action"
          value={results.nextAction}
          iconColor="text-orange-400"
          delay={300}
        />
        <ResultsCard
          icon={FileText}
          label="Summary"
          value={results.summary}
          iconColor="text-green-400"
          delay={400}
        />
        <ResultsCard
          icon={MessageCircle}
          label="Suggested Reply"
          value={results.suggestedReply}
          iconColor="text-pink-400"
          delay={500}
        />
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center items-center animate-scale-in">
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          className="ios-glass-button px-8 py-3 rounded-2xl font-semibold flex items-center gap-2 hover:scale-105 transition-all duration-300"
        >
          <Home size={20} />
          Back to Home
        </button>
        <button
          onClick={onReset}
          className="ios-glass-button px-8 py-3 rounded-2xl font-semibold flex items-center gap-2 hover:scale-105 transition-all duration-300"
        >
          <RotateCcw size={20} />
          Try Another
        </button>
      </div>
    </section>
  );
};

export default ResultsDashboard;
